[package]
name = "serde_utils"
version = "0.2.1"
authors = ["Michael Chesser"]
edition = "2018"

[features]
default = []

[dependencies]
serde = "1.0.104"
hex = { version = "0.4.2", optional = true }
base64 = { version = "0.12.0", optional = true }
byteorder = "1.3.4"
