[package]
name = "serde_utils"
version = "0.1.0"
authors = ["Michael Chesser"]
edition = "2018"

[features]
default = []

[dependencies]
serde = "1.0.91"
hex = { version = "0.3.2", optional = true }
base64 = { version = "0.10.1", optional = true }
byteorder = "1.3.1"
